# Generated by Django 5.1.6 on 2025-03-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_paymentmethod_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
