# Generated by Django 5.1.6 on 2025-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroplane', '0005_remove_checkoutsession_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='stripe_session_id',
            field=models.CharField(default='222', max_length=255),
        ),
    ]
