# Generated by Django 5.1.6 on 2025-03-14 00:02

import django.core.validators
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroplane', '0008_remove_checkoutsession_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('name', models.CharField(help_text='Name of the holiday deal (e.g., Ramadan Sale)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the deal', null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage off the product price (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(help_text='Start date and time of the deal')),
                ('end_date', models.DateTimeField(help_text='End date and time of the deal')),
                ('is_active', models.BooleanField(default=False, editable=False, help_text='Automatically set based on start/end dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(help_text='Products included in this deal', related_name='holiday_deals', to='aeroplane.product')),
            ],
            options={
                'verbose_name': 'Holiday Deal',
                'verbose_name_plural': 'Holiday Deals',
                'ordering': ['-start_date'],
            },
        ),
    ]
